-- ghostty-mirror.nvim
-- Mirror Neovim's colorscheme into Ghostty so the terminal flips themes the
-- moment you change colorschemes in nvim.

local M = {}

---@class GhosttyMirrorConfig
---@field themes_dir string Directory Ghostty reads themes from. Defaults to ~/.config/ghostty/themes.
---@field theme_file string Path Ghostty reads the active theme from via config-file include. Defaults to ~/.config/ghostty/theme-current.
---@field light_variant_suffix string Suffix used when looking for light-mode variant files (e.g. "cyberdream-light"). Set to "" or false to disable.
---@field generate boolean When no theme file exists for a colorscheme, generate one on the fly from Neovim's live highlights and terminal_color_* palette, caching it to themes_dir. Skips silently if the palette is incomplete. Defaults to true.
---@field reload_command string[] Command + args used to tell Ghostty to reload its config. Defaults to `pkill -SIGUSR2 ghostty`.
---@field debounce_ms integer Coalesce rapid :colorscheme changes (e.g. a picker's live preview) and only mirror once the scheme settles, this many ms after the last change. 0 mirrors synchronously on every change. Defaults to 150.
---@field manage_background boolean Opt-in: keep &background honest across :colorscheme switches. Baselines &background to dark before a scheme loads (so &background-adaptive schemes like `default` don't inherit a stale light from a previous light scheme) then syncs it to the loaded scheme's Normal-bg luminance. Defaults to false.
---@field sync_on_startup boolean Opt-in: on setup (or VimEnter), apply the colorscheme named in theme_file so a freshly-opened nvim follows Ghostty's current theme. Defaults to false.
---@field sync_on_focus boolean Opt-in: on FocusGained, apply the colorscheme named in theme_file when it differs from the one this instance loaded, so multiple nvim instances re-sync to whichever last wrote the theme. Defaults to false.
---@field tmux GhosttyMirrorTmuxConfig Opt-in tmux statusline mirroring. Disabled by default.

---@class GhosttyMirrorTmuxConfig
---@field enabled boolean Mirror the colorscheme into tmux's statusline on :colorscheme. Defaults to false (opt-in).
---@field themes_dir string Directory tmux theme files live in / are cached to. Defaults to ~/.config/tmux/themes.
---@field theme_file string Pointer file tmux sources; the plugin writes `source-file <themes_dir>/<name>.conf` here. Defaults to ~/.config/tmux/theme-current.conf.
---@field generate boolean Generate a tmux theme from live highlights when no hand-made file exists. Defaults to true.
---@field reload_command string[]|nil Command to apply the theme to the running tmux server. nil uses `tmux source-file <theme_file>`.
---@field bar_blend number How far the status bar blends from Normal's background toward the accent, 0..1 (keeps it in-hue rather than greying toward white). Defaults to 0.22.
---@field accent_hl string Highlight group whose fg is the bright accent (selected window, active divider, status-right). Sourcing it from a highlight lets the accent harmonize with each scheme's own hue. Defaults to "Type".
---@field divider_hl string Highlight group whose fg colors the inactive pane border. Defaults to "WinSeparator".
---@field overrides table<string, { accent?: string, divider?: string, bar_blend?: number }> Per-theme tweaks merged into generation, keyed by resolved theme name (the light variant keys separately, e.g. "ron-light"). Colors accept "#rgb"/"#rrggbb". Defaults to {}.

---@type GhosttyMirrorConfig
local defaults = {
	themes_dir = vim.fn.expand("~/.config/ghostty/themes"),
	theme_file = vim.fn.expand("~/.config/ghostty/theme-current"),
	light_variant_suffix = "-light",
	generate = true,
	reload_command = { "pkill", "-SIGUSR2", "ghostty" },
	debounce_ms = 150,
	manage_background = false,
	sync_on_startup = false,
	sync_on_focus = false,
	tmux = {
		enabled = false,
		themes_dir = vim.fn.expand("~/.config/tmux/themes"),
		theme_file = vim.fn.expand("~/.config/tmux/theme-current.conf"),
		generate = true,
		reload_command = nil,
		bar_blend = 0.22,
		accent_hl = "Type",
		divider_hl = "WinSeparator",
		overrides = {},
	},
}

---@type GhosttyMirrorConfig
M.config = vim.deepcopy(defaults)

-- Header on every generated theme file. Marks a file as plugin-owned so we can
-- safely delete it on cache clear without touching hand-made themes.
local generated_marker = "# Generated by ghostty-mirror.nvim"

---Whether a colorscheme name is safe to use as a theme file name and inside
---the Ghostty/tmux pointer files. The name flows into filesystem paths, a
---Ghostty config line and a tmux `source-file` command, so anything beyond
---word chars, dot, underscore and dash (path separators, quotes, newlines)
---is refused — fail silently, never wrongly.
---@param name string
---@return boolean
local function valid_name(name) return name:match("^[%w._%-]+$") ~= nil end

---Whether a theme file is plugin-generated (its first line is the marker).
---@param path string
---@return boolean
local function is_generated(path)
	local first = vim.fn.readfile(path, "", 1)[1]
	return first ~= nil and vim.startswith(first, generated_marker)
end

---Convert a 24-bit color integer (as returned by nvim_get_hl) to "#rrggbb".
---@param n integer|nil
---@return string|nil
local function hex(n)
	if type(n) ~= "number" then return nil end
	return string.format("#%06x", n)
end

---Resolve a highlight group to its effective fg/bg, following links.
---@param name string
---@return table
local function hl(name) return vim.api.nvim_get_hl(0, { name = name, link = false }) end

---Channels of a "#rrggbb" color.
---@param color string
---@return integer, integer, integer
local function rgb(color)
	return tonumber(color:sub(2, 3), 16), tonumber(color:sub(4, 5), 16), tonumber(color:sub(6, 7), 16)
end

---Perceived luminance of a "#rrggbb" color, 0 (black) .. 1 (white).
---@param color string
---@return number
local function luminance(color)
	local r, g, b = rgb(color)
	return (0.299 * r + 0.587 * g + 0.114 * b) / 255
end

---Blend color `a` toward color `b` by t (0..1): 0 returns `a`, 1 returns `b`.
---@param a string # "#rrggbb"
---@param b string # "#rrggbb"
---@param t number
---@return string
local function blend(a, b, t)
	local ar, ag, ab = rgb(a)
	local br, bg, bb = rgb(b)
	local function mix(x, y) return math.floor(x + (y - x) * t + 0.5) end
	return string.format("#%02x%02x%02x", mix(ar, br), mix(ag, bg), mix(ab, bb))
end

---Normalize a user-supplied color to lowercase "#rrggbb": expands "#rgb"
---shorthand, returns nil for anything else so bad values drop silently.
---@param color any
---@return string|nil
local function normalize_color(color)
	if type(color) ~= "string" then return nil end
	color = color:lower()
	local r, g, b = color:match("^#(%x)(%x)(%x)$")
	if r then return "#" .. r .. r .. g .. g .. b .. b end
	return color:match("^#%x%x%x%x%x%x$")
end

---Return whichever of two candidates reads better on `color`: the lighter one
---on a dark color, the darker one on a light color. Picks by actual luminance
---(not by assuming which candidate is light), so it's correct on light themes
---where Normal's fg is the dark one.
---@param color string
---@param x string
---@param y string
---@return string
local function readable_on(color, x, y)
	local lighter, darker = x, y
	if luminance(y) > luminance(x) then
		lighter, darker = y, x
	end
	return luminance(color) < 0.5 and lighter or darker
end

---Snapshot the live terminal palette (g:terminal_color_0..15).
---@return table<integer, string|nil>
local function snapshot_palette()
	local p = {}
	for i = 0, 15 do
		p[i] = vim.g["terminal_color_" .. i]
	end
	return p
end

---Whether two palette snapshots hold identical values across all 16 slots.
---@param a table<integer, string|nil>
---@param b table<integer, string|nil>
---@return boolean
local function palettes_equal(a, b)
	for i = 0, 15 do
		if a[i] ~= b[i] then return false end
	end
	return true
end

---Whether a palette snapshot has a non-empty string in all 16 slots.
---@param p table<integer, string|nil>
---@return boolean
local function palette_complete(p)
	for i = 0, 15 do
		if type(p[i]) ~= "string" or p[i] == "" then return false end
	end
	return true
end

-- g:terminal_color_* is global and sticky: it survives :colorscheme changes,
-- so a scheme that defines no palette of its own inherits whatever the previous
-- scheme left behind. We snapshot it on ColorSchemePre and only trust it when
-- the new scheme actually changed it, so we never mirror a palette that doesn't
-- belong to the current colorscheme.
local prev_palette
local palette_owned = true

-- Pending debounced push; a colorscheme picker's live preview fires a
-- ColorScheme per previewed scheme, so we coalesce them and only mirror once
-- the scheme settles (see config.debounce_ms).
local push_timer

-- The colorscheme name from the last ColorScheme event's `match`. This is the
-- name as loaded (`cyberdream-light`), which can differ from `g:colors_name`
-- (some schemes, e.g. cyberdream, set it to a base name like `cyberdream` for
-- every variant). The force commands prefer this so they mirror the variant
-- actually on screen.
local last_scheme

---Cancel the pending debounced push, if any.
local function cancel_pending_push()
	if push_timer then
		push_timer:stop()
		push_timer:close()
		push_timer = nil
	end
end

---Mirror `colorscheme`, debounced by config.debounce_ms. A new change cancels
---the pending one, so only the settled scheme is pushed. 0 pushes immediately.
---@param colorscheme string
local function schedule_push(colorscheme)
	local delay = tonumber(M.config.debounce_ms) or 0
	if delay <= 0 then
		M.push(colorscheme)
		return
	end
	cancel_pending_push()
	local timer = vim.uv.new_timer()
	push_timer = timer
	timer:start(
		delay,
		0,
		vim.schedule_wrap(function()
			-- The cancel may have closed this timer while the callback sat in the
			-- schedule queue; a fired-but-cancelled push must stay cancelled.
			if timer:is_closing() then return end
			timer:close()
			if push_timer == timer then push_timer = nil end
			M.push(colorscheme)
		end)
	)
end

---Name we'd write a generated theme under, honoring the light variant suffix
---when &background is "light" so light/dark caches stay separate.
---@param colorscheme string
---@return string
local function target_name(colorscheme)
	local cfg = M.config
	if cfg.light_variant_suffix and cfg.light_variant_suffix ~= "" and vim.o.background == "light" then
		return colorscheme .. cfg.light_variant_suffix
	end
	return colorscheme
end

---The normalized per-theme tmux overrides that actually take effect for a
---resolved theme name; invalid values are absent so generation falls back.
---@param name string
---@return { accent?: string, divider?: string, bar_blend?: number }
local function effective_overrides(name)
	local entry = M.config.tmux.overrides[name] or {}
	return {
		accent = normalize_color(entry.accent),
		divider = normalize_color(entry.divider),
		bar_blend = type(entry.bar_blend) == "number" and entry.bar_blend or nil,
	}
end

---Deterministic one-line stamp of an override set (sorted keys, normalized
---values), embedded in generated files so a config edit is detectable as a
---stale cache. nil when the set is empty.
---@param o table<string, string|number>
---@return string|nil
local function serialize_overrides(o)
	local keys = vim.tbl_keys(o)
	table.sort(keys)
	local parts = {}
	for _, k in ipairs(keys) do
		parts[#parts + 1] = ("%s=%s"):format(k, type(o[k]) == "number" and ("%g"):format(o[k]) or o[k])
	end
	if #parts == 0 then return nil end
	return "# overrides: " .. table.concat(parts, ",")
end

---Build the lines of a Ghostty theme file from Neovim's *live* highlight state
---(the currently loaded colorscheme). Returns nil only when the colorscheme has
---no Normal fg/bg to anchor the theme. The highlight-derived colors (background,
---foreground, cursor, selection) are always the scheme's own, so they're mirrored
---unconditionally; the 16-color palette is only appended when this scheme owns a
---full one (see `palette_owned`), since terminal_color_* is global and sticky and
---a scheme that sets none of its own would otherwise mirror an inherited palette.
---@param colorscheme string
---@return string[]|nil
function M.generate(colorscheme)
	local normal = hl("Normal")
	local bg, fg = hex(normal.bg), hex(normal.fg)
	if not bg or not fg then return nil end

	local lines = {
		generated_marker .. " from nvim colorscheme: " .. colorscheme,
		"background = " .. bg,
		"foreground = " .. fg,
	}

	local cursor = hl("Cursor")
	local cc = hex(cursor.bg) or hex(cursor.fg)
	if cc then table.insert(lines, "cursor-color = " .. cc) end
	-- cursor-text is the glyph color under the block cursor; only meaningful when
	-- the cursor owns a bg (so cursor-color above came from bg, not from fg).
	local ct = hex(cursor.fg)
	if ct and cursor.bg then table.insert(lines, "cursor-text = " .. ct) end

	local visual = hl("Visual")
	local sel = hex(visual.bg)
	if sel then table.insert(lines, "selection-background = " .. sel) end
	local sel_fg = hex(visual.fg)
	if sel_fg then table.insert(lines, "selection-foreground = " .. sel_fg) end

	local palette = snapshot_palette()
	if palette_owned and palette_complete(palette) then
		table.insert(lines, "")
		for i = 0, 15 do
			table.insert(lines, "palette = " .. i .. "=" .. palette[i])
		end
	end
	return lines
end

---Build the lines of a tmux theme file (a list of `set -g *-style` commands)
---from Neovim's live highlights. Returns nil only when Normal has no fg/bg to
---anchor the theme. The status bar is the background "a little lighter"; the
---bright accent (selected window + active pane border) comes from the scheme's
---ANSI slot when it owns a full palette, else from a syntax highlight group.
---@param colorscheme string
---@return string[]|nil
function M.generate_tmux(colorscheme)
	local normal = hl("Normal")
	local bg, fg = hex(normal.bg), hex(normal.fg)
	if not bg or not fg then return nil end

	local cfg = M.config.tmux
	local o = effective_overrides(target_name(colorscheme))

	-- The accent can't be inferred from the background, so it's opinionated: a
	-- syntax highlight group's fg. Sourcing it from a highlight (not a fixed ANSI
	-- slot) lets it harmonize with the scheme's own hue — magenta-ish on a purple
	-- theme, blue on a blue one — instead of forcing one hue on every theme.
	local accent = o.accent or hex(hl(cfg.accent_hl).fg) or fg

	-- The status bar is the background nudged for contrast: on a dark theme,
	-- toward the accent (stays in-hue and saturated); on a light theme, toward
	-- the foreground, since a light bg blended toward a mid-tone accent barely
	-- moves and washes out. Selected-window text takes whichever of fg/bg reads
	-- on the accent.
	local light = luminance(bg) > 0.5
	local bar = blend(bg, light and fg or accent, o.bar_blend or cfg.bar_blend)
	local accent_fg = readable_on(accent, fg, bg)
	local divider = o.divider or hex(hl(cfg.divider_hl).fg) or accent

	local bar_pair = ("bg=%s,fg=%s"):format(bar, fg)
	local accent_pair = ("bg=%s,fg=%s"):format(accent, accent_fg)
	-- Style every base segment (incl. status-left, which tmux leaves at the
	-- theme default otherwise) with the bar color so the bar reads as one piece.
	-- On a light theme the accent appears only on the current window; on a dark
	-- theme status-right stays an accent pill.
	local right_pair = light and bar_pair or accent_pair

	local lines = {
		generated_marker .. " from nvim colorscheme: " .. colorscheme,
		('set -g status-style "%s"'):format(bar_pair),
		('set -g status-left-style "%s"'):format(bar_pair),
		('set -g status-right-style "%s"'):format(right_pair),
		('set -g window-status-style "%s"'):format(bar_pair),
		('set -g window-status-current-style "%s"'):format(accent_pair),
		('set -g pane-active-border-style "fg=%s"'):format(accent),
		('set -g pane-border-style "fg=%s"'):format(divider),
		('set -g message-style "%s"'):format(bar_pair),
		('set -g message-command-style "%s"'):format(bar_pair),
		('set -g mode-style "%s"'):format(accent_pair),
		('set -g clock-mode-colour "%s"'):format(accent),
	}
	-- Stamp the overrides that shaped this file so resolve_tmux can tell a
	-- cache generated under a different config from a current one.
	local stamp = serialize_overrides(o)
	if stamp then table.insert(lines, 2, stamp) end
	return lines
end

---Generate a theme from live highlights and write it to themes_dir.
---@param colorscheme string
---@return string|nil # the theme name written, or nil if generation wasn't possible
function M.write_generated(colorscheme)
	local lines = M.generate(colorscheme)
	if not lines then return nil end
	local name = target_name(colorscheme)
	vim.fn.mkdir(M.config.themes_dir, "p")
	vim.fn.writefile(lines, M.config.themes_dir .. "/" .. name)
	return name
end

---Generate a tmux theme from live highlights and write it to tmux.themes_dir as
---`<name>.conf`.
---@param colorscheme string
---@return string|nil # the theme name written, or nil if generation wasn't possible
function M.write_tmux_generated(colorscheme)
	local lines = M.generate_tmux(colorscheme)
	if not lines then return nil end
	local name = target_name(colorscheme)
	vim.fn.mkdir(M.config.tmux.themes_dir, "p")
	vim.fn.writefile(lines, M.config.tmux.themes_dir .. "/" .. name .. ".conf")
	return name
end

---Whether a tmux theme file is still the one we'd generate today: hand-made
---files are always current (the user owns them), a generated file is current
---only when its override stamp matches the overrides now configured for it.
---@param path string
---@param name string # resolved theme name the file serves
---@return boolean
local function tmux_cache_current(path, name)
	if not is_generated(path) then return true end
	local second = vim.fn.readfile(path, "", 2)[2]
	local stamp = second ~= nil and vim.startswith(second, "# overrides:") and second or nil
	return stamp == serialize_overrides(effective_overrides(name))
end

---Resolve the tmux theme name for a colorscheme. Same precedence as `resolve`:
---a hand-made `<name>.conf` wins (honoring the light variant suffix), otherwise
---one is generated from live highlights and cached. A generated cache whose
---override stamp no longer matches the config is regenerated, so override
---edits take effect on the next push.
---@param colorscheme string
---@return string|nil # resolved theme name, nil when nothing resolves
---@return boolean|nil # true when the theme file was (re)generated by this call
function M.resolve_tmux(colorscheme)
	if not valid_name(colorscheme) then return nil end
	local cfg = M.config.tmux
	local suffix = M.config.light_variant_suffix
	local light = suffix and suffix ~= "" and vim.o.background == "light"
	-- A stale cache only loses to regeneration when regenerating is possible.
	local function usable(path, name) return tmux_cache_current(path, name) or not cfg.generate end
	if light then
		local variant = cfg.themes_dir .. "/" .. colorscheme .. suffix .. ".conf"
		if vim.uv.fs_stat(variant) and usable(variant, colorscheme .. suffix) then return colorscheme .. suffix end
	end
	-- Same as `resolve`: a generated bare .conf was built for dark, so don't
	-- mirror it under a light colorscheme — regenerate the light variant instead.
	local bare = cfg.themes_dir .. "/" .. colorscheme .. ".conf"
	if vim.uv.fs_stat(bare) and not (light and is_generated(bare)) and usable(bare, colorscheme) then
		return colorscheme
	end
	if cfg.generate then
		local name = M.write_tmux_generated(colorscheme)
		return name, name ~= nil
	end
	return nil
end

---Resolve the Ghostty theme name to write for a given Neovim colorscheme.
---Precedence: a hand-made/cached file wins (honoring the light variant suffix
---when &background is "light"); otherwise, if `generate` is enabled, a theme is
---built on the fly from live highlights and cached to themes_dir.
---@param colorscheme string
---@return string|nil # nil if no file exists and generation isn't possible
function M.resolve(colorscheme)
	if not valid_name(colorscheme) then return nil end
	local cfg = M.config
	local light = cfg.light_variant_suffix and cfg.light_variant_suffix ~= "" and vim.o.background == "light"
	if light then
		local variant = cfg.themes_dir .. "/" .. colorscheme .. cfg.light_variant_suffix
		if vim.uv.fs_stat(variant) then return colorscheme .. cfg.light_variant_suffix end
	end
	-- The bare <name> file is a valid fallback only when it's hand-made. A
	-- *generated* bare file was built for a dark background (Normal and
	-- terminal_color_* flip with &background), so reusing it in light mode would
	-- mirror the dark theme under a light colorscheme. Skip it and regenerate the
	-- light variant instead.
	local bare = cfg.themes_dir .. "/" .. colorscheme
	if vim.uv.fs_stat(bare) and not (light and is_generated(bare)) then return colorscheme end
	if cfg.generate then return M.write_generated(colorscheme) end
	return nil
end

---Write the resolved theme to the theme file and signal Ghostty to reload.
---@param colorscheme string
---@param opts? { force?: boolean } # force regenerates from live highlights, ignoring any existing file
---@return string|nil # the theme name written, or nil when nothing was written
function M.push(colorscheme, opts)
	-- No scheme to mirror (e.g. an aborted colorscheme load leaves colors_name
	-- nil): no-op rather than writing a bogus `theme =` line Ghostty can't load.
	if not colorscheme or not valid_name(colorscheme) then return end
	local name
	if opts and opts.force then
		-- An explicit force trusts whatever palette is live right now.
		palette_owned = true
		name = M.write_generated(colorscheme)
	else
		name = M.resolve(colorscheme)
	end
	if not name then return end
	-- Skip the rewrite + reload when Ghostty already points at this exact theme:
	-- SIGUSR2 reloads *every* Ghostty window, so spurious reloads (idempotent
	-- :colorscheme, a background re-apply cascade) aren't free. Safe because the
	-- non-force path never regenerates an existing cache, so the file Ghostty
	-- already loaded is byte-identical. Force always rewrites and reloads.
	if (opts and opts.force) or M.read_current() ~= name then
		vim.fn.writefile({ "theme = " .. name }, M.config.theme_file)
		vim.system(M.config.reload_command, { detach = true })
	end
	if M.config.tmux.enabled then M.push_tmux(colorscheme, opts) end
	return name
end

---Resolve the tmux theme for a colorscheme, point tmux.theme_file at it, and
---tell the running tmux server to source it. No-op (no reload) when nothing
---resolves. Fails silently if no tmux server is running.
---@param colorscheme string
---@param opts? { force?: boolean }
---@return string|nil # the theme name written, or nil when nothing was written
function M.push_tmux(colorscheme, opts)
	if not colorscheme or not valid_name(colorscheme) then return end
	local cfg = M.config.tmux
	local name, regenerated
	if opts and opts.force then
		palette_owned = true
		name = M.write_tmux_generated(colorscheme)
	else
		name, regenerated = M.resolve_tmux(colorscheme)
	end
	if not name then return end
	-- Same idempotence as M.push: skip the source + reload when tmux already
	-- sources this exact theme (force always re-sources). A cache regenerated
	-- under an unchanged pointer still reloads — the file content changed.
	local line = 'source-file "' .. cfg.themes_dir .. "/" .. name .. '.conf"'
	local current = vim.fn.filereadable(cfg.theme_file) == 1 and vim.fn.readfile(cfg.theme_file)[1] or nil
	if (opts and opts.force) or regenerated or current ~= line then
		vim.fn.writefile({ line }, cfg.theme_file)
		vim.system(cfg.reload_command or { "tmux", "source-file", cfg.theme_file }, { detach = true })
	end
	return name
end

---Delete every generated file (first line is the generated marker) from a dir,
---leaving hand-made files untouched. Missing dirs are skipped.
---@param dir string
---@return string[]
local function clear_generated_in(dir)
	local cleared = {}
	if not (dir and vim.uv.fs_stat(dir)) then return cleared end
	for name, type in vim.fs.dir(dir) do
		if type == "file" and is_generated(dir .. "/" .. name) then
			vim.fn.delete(dir .. "/" .. name)
			table.insert(cleared, name)
		end
	end
	return cleared
end

---Delete every generated theme file from themes_dir (and the tmux themes_dir
---when tmux mirroring is enabled), leaving hand-made files untouched. A file is
---plugin-owned when its first line is the generated marker, so stale caches can
---be cleared without risking the user's own themes.
---@return string[] # names of the files deleted
function M.clear_cache()
	local cleared = clear_generated_in(M.config.themes_dir)
	if M.config.tmux.enabled then vim.list_extend(cleared, clear_generated_in(M.config.tmux.themes_dir)) end
	return cleared
end

---Read the theme name currently set in Ghostty's theme-current file.
---@return string|nil
function M.read_current()
	if vim.fn.filereadable(M.config.theme_file) ~= 1 then return nil end
	for _, line in ipairs(vim.fn.readfile(M.config.theme_file)) do
		local name = line:match("theme%s*=%s*(%S+)")
		if name then return name end
	end
	return nil
end

---Apply the colorscheme stored in Ghostty's theme-current file to this Neovim
---instance. Used to pull the active theme into other nvim instances.
function M.pull()
	local theme = M.read_current()
	if not theme then
		vim.notify("ghostty-mirror: could not read theme from " .. M.config.theme_file, vim.log.levels.WARN)
		return
	end
	vim.cmd.colorscheme(theme)
end

---The colorscheme name to act on for the force commands: the last settled
---ColorScheme `match` if one has fired, else `g:colors_name`. Prefers the
---event match because some schemes set `g:colors_name` to a base name shared
---across variants, which would mirror the wrong file.
---@return string
function M.current_scheme() return last_scheme or vim.g.colors_name or "" end

-- Expected type per config field; "string|false" admits the disable sentinel.
-- Hand-rolled (not vim.validate) to stay stable across the 0.11+ signature churn.
local config_types = {
	themes_dir = "string",
	theme_file = "string",
	light_variant_suffix = "string|false",
	generate = "boolean",
	reload_command = "table",
	debounce_ms = "number",
	manage_background = "boolean",
	sync_on_startup = "boolean",
	sync_on_focus = "boolean",
	tmux = "table",
}

local tmux_config_types = {
	enabled = "boolean",
	themes_dir = "string",
	theme_file = "string",
	generate = "boolean",
	reload_command = "table|nil",
	bar_blend = "number",
	accent_hl = "string",
	divider_hl = "string",
	overrides = "table",
}

---Fail fast on a misshapen config (e.g. `tmux = true`) with a clear message,
---rather than erroring deep inside a later push.
---@param cfg table
---@param types table<string, string>
---@param prefix string
local function validate_config(cfg, types, prefix)
	for field, want in pairs(types) do
		local v = cfg[field]
		local ok = (want:find(type(v), 1, true) ~= nil) or (want:find("false", 1, true) and v == false)
		if not ok then
			error(("ghostty-mirror: config.%s%s must be %s, got %s"):format(prefix, field, want, type(v)), 0)
		end
	end
end

-- Recognized per-theme tmux override params and their expected kind.
local override_params = { accent = "color", divider = "color", bar_blend = "number" }

---Warn (don't error) about override entries that can't take effect: a typo'd
---param or a malformed value would otherwise be ignored without a trace.
---@param overrides table<string, table>
local function validate_overrides(overrides)
	local function warn(fmt, ...) vim.notify("ghostty-mirror: " .. fmt:format(...), vim.log.levels.WARN) end
	-- Override keys are *resolved* names: the light variant carries the suffix
	-- without being a colorscheme of its own, so accept "<scheme><suffix>" too.
	local known = {}
	for _, scheme in ipairs(vim.fn.getcompletion("", "color")) do
		known[scheme] = true
	end
	local suffix = M.config.light_variant_suffix
	for name, entry in pairs(overrides) do
		local base = suffix and suffix ~= "" and name:sub(-#suffix) == suffix and name:sub(1, -#suffix - 1)
		if not (known[name] or known[base]) then
			warn('tmux override for "%s" matches no installed colorscheme', name)
		end
		for param, value in pairs(entry) do
			local kind = override_params[param]
			local invalid = (kind == "color" and not normalize_color(value))
				or (kind == "number" and type(value) ~= "number")
			if not kind then
				warn('unknown tmux override param "%s" for theme "%s"', param, name)
			elseif invalid then
				warn('invalid tmux override %s value "%s" for theme "%s"', param, tostring(value), name)
			end
		end
	end
end

---@param opts? GhosttyMirrorConfig
function M.setup(opts)
	-- vim.uv and nvim_get_hl{ link = false } need 0.10; bail loudly rather than
	-- erroring obscurely on the first colorscheme change.
	if vim.fn.has("nvim-0.10") ~= 1 then
		vim.notify("ghostty-mirror requires Neovim 0.10+", vim.log.levels.ERROR)
		return
	end

	M.config = vim.tbl_deep_extend("force", defaults, opts or {})
	validate_config(M.config, config_types, "")
	validate_config(M.config.tmux, tmux_config_types, "tmux.")
	validate_overrides(M.config.tmux.overrides)

	-- Re-setup is advertised as idempotent: a debounce armed under the old
	-- config must not fire a stale push under the new one.
	cancel_pending_push()

	local group = vim.api.nvim_create_augroup("ghostty-mirror", { clear = true })

	-- A debounce can also be pending at shutdown; don't push into a dying editor.
	vim.api.nvim_create_autocmd("VimLeavePre", {
		group = group,
		callback = cancel_pending_push,
	})

	vim.api.nvim_create_autocmd("ColorSchemePre", {
		group = group,
		callback = function() prev_palette = snapshot_palette() end,
	})

	vim.api.nvim_create_autocmd("ColorScheme", {
		group = group,
		callback = function(ev)
			last_scheme = ev.match
			local cur = snapshot_palette()
			palette_owned = prev_palette == nil or not palettes_equal(prev_palette, cur)
			schedule_push(ev.match)
		end,
	})

	if M.config.manage_background then
		-- Writing &background re-applies the current scheme (and re-fires these
		-- events), so guard every write to stop the two hooks looping.
		local adjusting = false
		local function set_background(want)
			if vim.o.background ~= want then
				adjusting = true
				vim.o.background = want
				adjusting = false
			end
		end

		-- Baseline to dark before a scheme loads, so &background-adaptive schemes
		-- (e.g. the built-in `default`) don't inherit a stale "light" left by a
		-- previous light scheme and render their washed variant.
		vim.api.nvim_create_autocmd("ColorSchemePre", {
			group = group,
			callback = function()
				if not adjusting then set_background("dark") end
			end,
		})

		-- After the scheme settles, sync &background to its actual Normal-bg
		-- luminance, so a scheme that renders light without setting &background
		-- itself (e.g. cyberdream-light) ends up light.
		vim.api.nvim_create_autocmd("ColorScheme", {
			group = group,
			callback = function()
				if adjusting then return end
				local bg = hex(hl("Normal").bg)
				if bg then set_background(luminance(bg) > 0.5 and "light" or "dark") end
			end,
		})
	end

	vim.api.nvim_create_user_command("ThemeFromGhostty", M.pull, {
		desc = "Apply the colorscheme currently set in Ghostty's theme-current file",
	})

	vim.api.nvim_create_user_command("ThemeToGhostty", function() M.push(M.current_scheme(), { force = true }) end, {
		desc = "Regenerate the current colorscheme's Ghostty theme from live highlights",
	})

	vim.api.nvim_create_user_command("ThemeToTmux", function() M.push_tmux(M.current_scheme(), { force = true }) end, {
		desc = "Regenerate the current colorscheme's tmux theme from live highlights",
	})

	vim.api.nvim_create_user_command("ThemeCacheClear", function()
		local cleared = M.clear_cache()
		vim.notify(
			("ghostty-mirror: cleared %d generated theme%s"):format(#cleared, #cleared == 1 and "" or "s"),
			vim.log.levels.INFO
		)
	end, {
		desc = "Delete every generated Ghostty/tmux theme file (hand-made themes are left untouched)",
	})

	if M.config.sync_on_startup then
		-- Apply the theme Ghostty currently points at so a freshly-opened nvim
		-- follows it. Deferred to VimEnter when setup runs during startup, since
		-- plugin colorschemes aren't loaded yet; run now if we're already past it.
		-- pcall keeps a missing/uninstalled colorscheme from erroring on launch.
		local function startup_sync()
			if M.read_current() then pcall(M.pull) end
		end
		if vim.v.vim_did_enter == 1 then
			startup_sync()
		else
			vim.api.nvim_create_autocmd("VimEnter", { group = group, once = true, callback = startup_sync })
		end
	end

	if M.config.sync_on_focus then
		-- Re-sync to whichever instance last wrote the theme when this window
		-- regains focus. Only re-apply when it actually differs from what we
		-- loaded, so a focus in an already-synced window is a no-op.
		vim.api.nvim_create_autocmd("FocusGained", {
			group = group,
			callback = function()
				local theme = M.read_current()
				if theme and theme ~= M.current_scheme() then pcall(vim.cmd.colorscheme, theme) end
			end,
		})
	end
end

return M
