-- ghostty-mirror.nvim
-- Mirror Neovim's colorscheme into Ghostty so the terminal flips themes the
-- moment you change colorschemes in nvim.

local M = {}

---@class GhosttyMirrorConfig
---@field themes_dir string Directory Ghostty reads themes from. Defaults to ~/.config/ghostty/themes.
---@field theme_file string Path Ghostty reads the active theme from via config-file include. Defaults to ~/.config/ghostty/theme-current.
---@field light_variant_suffix string Suffix used when looking for light-mode variant files (e.g. "cyberdream-light"). Set to "" or false to disable.
---@field generate boolean When no theme file exists for a colorscheme, generate one on the fly from Neovim's live highlights and terminal_color_* palette, caching it to themes_dir. Skips silently if the palette is incomplete. Defaults to true.
---@field reload_command string[] Command + args used to tell Ghostty to reload its config. Defaults to `pkill -SIGUSR2 ghostty`.
---@field tmux GhosttyMirrorTmuxConfig Opt-in tmux statusline mirroring. Disabled by default.

---@class GhosttyMirrorTmuxConfig
---@field enabled boolean Mirror the colorscheme into tmux's statusline on :colorscheme. Defaults to false (opt-in).
---@field themes_dir string Directory tmux theme files live in / are cached to. Defaults to ~/.config/tmux/themes.
---@field theme_file string Pointer file tmux sources; the plugin writes `source-file <themes_dir>/<name>.conf` here. Defaults to ~/.config/tmux/theme-current.conf.
---@field generate boolean Generate a tmux theme from live highlights when no hand-made file exists. Defaults to true.
---@field reload_command string[]|nil Command to apply the theme to the running tmux server. nil uses `tmux source-file <theme_file>`.
---@field bar_blend number How far the status bar blends from Normal's background toward the accent, 0..1 (keeps it in-hue rather than greying toward white). Defaults to 0.22.
---@field accent_ansi integer ANSI palette slot (0..15) used for the bright accent (selected window, active divider) when the scheme owns a full palette. Defaults to 5 (magenta).
---@field accent_fallback_hl string Highlight group whose fg is used for the accent when the palette isn't owned/complete. Defaults to "Type".
---@field divider_hl string Highlight group whose fg colors the inactive pane border. Defaults to "WinSeparator".

---@type GhosttyMirrorConfig
local defaults = {
	themes_dir = vim.fn.expand("~/.config/ghostty/themes"),
	theme_file = vim.fn.expand("~/.config/ghostty/theme-current"),
	light_variant_suffix = "-light",
	generate = true,
	reload_command = { "pkill", "-SIGUSR2", "ghostty" },
	tmux = {
		enabled = false,
		themes_dir = vim.fn.expand("~/.config/tmux/themes"),
		theme_file = vim.fn.expand("~/.config/tmux/theme-current.conf"),
		generate = true,
		reload_command = nil,
		bar_blend = 0.22,
		accent_ansi = 5,
		accent_fallback_hl = "Type",
		divider_hl = "WinSeparator",
	},
}

---@type GhosttyMirrorConfig
M.config = vim.deepcopy(defaults)

-- Header on every generated theme file. Marks a file as plugin-owned so we can
-- safely delete it on cache clear without touching hand-made themes.
local generated_marker = "# Generated by ghostty-mirror.nvim"

---Convert a 24-bit color integer (as returned by nvim_get_hl) to "#rrggbb".
---@param n integer|nil
---@return string|nil
local function hex(n)
	if type(n) ~= "number" then return nil end
	return string.format("#%06x", n)
end

---Resolve a highlight group to its effective fg/bg, following links.
---@param name string
---@return table
local function hl(name)
	return vim.api.nvim_get_hl(0, { name = name, link = false })
end

---Channels of a "#rrggbb" color.
---@param color string
---@return integer, integer, integer
local function rgb(color)
	return tonumber(color:sub(2, 3), 16), tonumber(color:sub(4, 5), 16), tonumber(color:sub(6, 7), 16)
end

---Blend color `a` toward color `b` by t (0..1): 0 returns `a`, 1 returns `b`.
---@param a string # "#rrggbb"
---@param b string # "#rrggbb"
---@param t number
---@return string
local function blend(a, b, t)
	local ar, ag, ab = rgb(a)
	local br, bg, bb = rgb(b)
	local function mix(x, y) return math.floor(x + (y - x) * t + 0.5) end
	return string.format("#%02x%02x%02x", mix(ar, br), mix(ag, bg), mix(ab, bb))
end

---Return whichever of `light`/`dark` reads better on `color`, by perceived
---luminance — so text on the accent stays legible whatever hue the accent is.
---@param color string
---@param light string
---@param dark string
---@return string
local function readable_on(color, light, dark)
	local r, g, b = rgb(color)
	return (0.299 * r + 0.587 * g + 0.114 * b) / 255 < 0.5 and light or dark
end

---Snapshot the live terminal palette (g:terminal_color_0..15).
---@return table<integer, string|nil>
local function snapshot_palette()
	local p = {}
	for i = 0, 15 do
		p[i] = vim.g["terminal_color_" .. i]
	end
	return p
end

---Whether two palette snapshots hold identical values across all 16 slots.
---@param a table<integer, string|nil>
---@param b table<integer, string|nil>
---@return boolean
local function palettes_equal(a, b)
	for i = 0, 15 do
		if a[i] ~= b[i] then return false end
	end
	return true
end

---Whether a palette snapshot has a non-empty string in all 16 slots.
---@param p table<integer, string|nil>
---@return boolean
local function palette_complete(p)
	for i = 0, 15 do
		if type(p[i]) ~= "string" or p[i] == "" then return false end
	end
	return true
end

-- g:terminal_color_* is global and sticky: it survives :colorscheme changes,
-- so a scheme that defines no palette of its own inherits whatever the previous
-- scheme left behind. We snapshot it on ColorSchemePre and only trust it when
-- the new scheme actually changed it, so we never mirror a palette that doesn't
-- belong to the current colorscheme.
local prev_palette
local palette_owned = true

---Name we'd write a generated theme under, honoring the light variant suffix
---when &background is "light" so light/dark caches stay separate.
---@param colorscheme string
---@return string
local function target_name(colorscheme)
	local cfg = M.config
	if cfg.light_variant_suffix and cfg.light_variant_suffix ~= "" and vim.o.background == "light" then
		return colorscheme .. cfg.light_variant_suffix
	end
	return colorscheme
end

---Build the lines of a Ghostty theme file from Neovim's *live* highlight state
---(the currently loaded colorscheme). Returns nil only when the colorscheme has
---no Normal fg/bg to anchor the theme. The highlight-derived colors (background,
---foreground, cursor, selection) are always the scheme's own, so they're mirrored
---unconditionally; the 16-color palette is only appended when this scheme owns a
---full one (see `palette_owned`), since terminal_color_* is global and sticky and
---a scheme that sets none of its own would otherwise mirror an inherited palette.
---@param colorscheme string
---@return string[]|nil
function M.generate(colorscheme)
	local normal = hl("Normal")
	local bg, fg = hex(normal.bg), hex(normal.fg)
	if not bg or not fg then return nil end

	local lines = {
		generated_marker .. " from nvim colorscheme: " .. colorscheme,
		"background = " .. bg,
		"foreground = " .. fg,
	}

	local cursor = hl("Cursor")
	local cc = hex(cursor.bg) or hex(cursor.fg)
	if cc then table.insert(lines, "cursor-color = " .. cc) end

	local visual = hl("Visual")
	local sel = hex(visual.bg)
	if sel then table.insert(lines, "selection-background = " .. sel) end

	local palette = snapshot_palette()
	if palette_owned and palette_complete(palette) then
		table.insert(lines, "")
		for i = 0, 15 do
			table.insert(lines, "palette = " .. i .. "=" .. palette[i])
		end
	end
	return lines
end

---Build the lines of a tmux theme file (a list of `set -g *-style` commands)
---from Neovim's live highlights. Returns nil only when Normal has no fg/bg to
---anchor the theme. The status bar is the background "a little lighter"; the
---bright accent (selected window + active pane border) comes from the scheme's
---ANSI slot when it owns a full palette, else from a syntax highlight group.
---@param colorscheme string
---@return string[]|nil
function M.generate_tmux(colorscheme)
	local normal = hl("Normal")
	local bg, fg = hex(normal.bg), hex(normal.fg)
	if not bg or not fg then return nil end

	local cfg = M.config.tmux

	-- The accent can't be inferred from the background, so it's opinionated: the
	-- scheme's own ANSI slot when it owns a full palette (never a stale/inherited
	-- one), otherwise a syntax highlight group that always belongs to the scheme.
	local palette = snapshot_palette()
	local accent
	if palette_owned and palette_complete(palette) then
		accent = palette[cfg.accent_ansi]
	end
	accent = accent or hex(hl(cfg.accent_fallback_hl).fg) or fg

	-- The status bar is the background nudged toward the accent (not toward
	-- white) so it stays in-hue and saturated. Selected-window text takes
	-- whichever of fg/bg reads on the accent.
	local bar = blend(bg, accent, cfg.bar_blend)
	local accent_fg = readable_on(accent, fg, bg)
	local divider = hex(hl(cfg.divider_hl).fg) or accent

	return {
		generated_marker .. " from nvim colorscheme: " .. colorscheme,
		('set -g status-style "bg=%s,fg=%s"'):format(bar, fg),
		('set -g window-status-style "bg=%s,fg=%s"'):format(bar, fg),
		('set -g window-status-current-style "bg=%s,fg=%s"'):format(accent, accent_fg),
		('set -g pane-active-border-style "fg=%s"'):format(accent),
		('set -g pane-border-style "fg=%s"'):format(divider),
		('set -g message-style "bg=%s,fg=%s"'):format(bar, fg),
		('set -g message-command-style "bg=%s,fg=%s"'):format(bar, fg),
		('set -g mode-style "bg=%s,fg=%s"'):format(accent, accent_fg),
		('set -g clock-mode-colour "%s"'):format(accent),
	}
end

---Generate a theme from live highlights and write it to themes_dir.
---@param colorscheme string
---@return string|nil # the theme name written, or nil if generation wasn't possible
function M.write_generated(colorscheme)
	local lines = M.generate(colorscheme)
	if not lines then return nil end
	local name = target_name(colorscheme)
	vim.fn.mkdir(M.config.themes_dir, "p")
	vim.fn.writefile(lines, M.config.themes_dir .. "/" .. name)
	return name
end

---Generate a tmux theme from live highlights and write it to tmux.themes_dir as
---`<name>.conf`.
---@param colorscheme string
---@return string|nil # the theme name written, or nil if generation wasn't possible
function M.write_tmux_generated(colorscheme)
	local lines = M.generate_tmux(colorscheme)
	if not lines then return nil end
	local name = target_name(colorscheme)
	vim.fn.mkdir(M.config.tmux.themes_dir, "p")
	vim.fn.writefile(lines, M.config.tmux.themes_dir .. "/" .. name .. ".conf")
	return name
end

---Resolve the tmux theme name for a colorscheme. Same precedence as `resolve`:
---a hand-made `<name>.conf` wins (honoring the light variant suffix), otherwise
---one is generated from live highlights and cached.
---@param colorscheme string
---@return string|nil
function M.resolve_tmux(colorscheme)
	local cfg = M.config.tmux
	local suffix = M.config.light_variant_suffix
	local name = colorscheme
	if
		suffix
		and suffix ~= ""
		and vim.o.background == "light"
		and vim.uv.fs_stat(cfg.themes_dir .. "/" .. name .. suffix .. ".conf")
	then
		name = name .. suffix
	end
	if vim.uv.fs_stat(cfg.themes_dir .. "/" .. name .. ".conf") then
		return name
	end
	if cfg.generate then
		return M.write_tmux_generated(colorscheme)
	end
	return nil
end

---Resolve the Ghostty theme name to write for a given Neovim colorscheme.
---Precedence: a hand-made/cached file wins (honoring the light variant suffix
---when &background is "light"); otherwise, if `generate` is enabled, a theme is
---built on the fly from live highlights and cached to themes_dir.
---@param colorscheme string
---@return string|nil # nil if no file exists and generation isn't possible
function M.resolve(colorscheme)
	local cfg = M.config
	local name = colorscheme
	if
		cfg.light_variant_suffix
		and cfg.light_variant_suffix ~= ""
		and vim.o.background == "light"
		and vim.uv.fs_stat(cfg.themes_dir .. "/" .. name .. cfg.light_variant_suffix)
	then
		name = name .. cfg.light_variant_suffix
	end
	if vim.uv.fs_stat(cfg.themes_dir .. "/" .. name) then
		return name
	end
	if cfg.generate then
		return M.write_generated(colorscheme)
	end
	return nil
end

---Write the resolved theme to the theme file and signal Ghostty to reload.
---@param colorscheme string
---@param opts? { force?: boolean } # force regenerates from live highlights, ignoring any existing file
---@return string|nil # the theme name written, or nil when nothing was written
function M.push(colorscheme, opts)
	local name
	if opts and opts.force then
		-- An explicit force trusts whatever palette is live right now.
		palette_owned = true
		name = M.write_generated(colorscheme)
	else
		name = M.resolve(colorscheme)
	end
	if not name then return end
	vim.fn.writefile({ "theme = " .. name }, M.config.theme_file)
	vim.system(M.config.reload_command, { detach = true })
	if M.config.tmux.enabled then M.push_tmux(colorscheme, opts) end
	return name
end

---Resolve the tmux theme for a colorscheme, point tmux.theme_file at it, and
---tell the running tmux server to source it. No-op (no reload) when nothing
---resolves. Fails silently if no tmux server is running.
---@param colorscheme string
---@param opts? { force?: boolean }
---@return string|nil # the theme name written, or nil when nothing was written
function M.push_tmux(colorscheme, opts)
	local cfg = M.config.tmux
	local name
	if opts and opts.force then
		palette_owned = true
		name = M.write_tmux_generated(colorscheme)
	else
		name = M.resolve_tmux(colorscheme)
	end
	if not name then return end
	vim.fn.writefile({ 'source-file "' .. cfg.themes_dir .. "/" .. name .. '.conf"' }, cfg.theme_file)
	vim.system(cfg.reload_command or { "tmux", "source-file", cfg.theme_file }, { detach = true })
	return name
end

---Delete every generated file (first line is the generated marker) from a dir,
---leaving hand-made files untouched. Missing dirs are skipped.
---@param dir string
---@return string[]
local function clear_generated_in(dir)
	local cleared = {}
	if not (dir and vim.uv.fs_stat(dir)) then return cleared end
	for name, type in vim.fs.dir(dir) do
		if type == "file" then
			local first = vim.fn.readfile(dir .. "/" .. name, "", 1)[1]
			if first and vim.startswith(first, generated_marker) then
				vim.fn.delete(dir .. "/" .. name)
				table.insert(cleared, name)
			end
		end
	end
	return cleared
end

---Delete every generated theme file from themes_dir (and the tmux themes_dir
---when tmux mirroring is enabled), leaving hand-made files untouched. A file is
---plugin-owned when its first line is the generated marker, so stale caches can
---be cleared without risking the user's own themes.
---@return string[] # names of the files deleted
function M.clear_cache()
	local cleared = clear_generated_in(M.config.themes_dir)
	if M.config.tmux.enabled then
		vim.list_extend(cleared, clear_generated_in(M.config.tmux.themes_dir))
	end
	return cleared
end

---Read the theme name currently set in Ghostty's theme-current file.
---@return string|nil
function M.read_current()
	if vim.fn.filereadable(M.config.theme_file) ~= 1 then return nil end
	local lines = vim.fn.readfile(M.config.theme_file)
	return lines[1] and lines[1]:match("theme%s*=%s*(%S+)") or nil
end

---Apply the colorscheme stored in Ghostty's theme-current file to this Neovim
---instance. Used to pull the active theme into other nvim instances.
function M.pull()
	local theme = M.read_current()
	if not theme then
		vim.notify(
			"ghostty-mirror: could not read theme from " .. M.config.theme_file,
			vim.log.levels.WARN
		)
		return
	end
	vim.cmd.colorscheme(theme)
end

---@param opts? GhosttyMirrorConfig
function M.setup(opts)
	M.config = vim.tbl_deep_extend("force", defaults, opts or {})

	local group = vim.api.nvim_create_augroup("ghostty-mirror", { clear = true })

	vim.api.nvim_create_autocmd("ColorSchemePre", {
		group = group,
		callback = function() prev_palette = snapshot_palette() end,
	})

	vim.api.nvim_create_autocmd("ColorScheme", {
		group = group,
		callback = function(ev)
			local cur = snapshot_palette()
			palette_owned = prev_palette == nil or not palettes_equal(prev_palette, cur)
			M.push(ev.match)
		end,
	})

	vim.api.nvim_create_user_command("ThemeFromGhostty", M.pull, {
		desc = "Apply the colorscheme currently set in Ghostty's theme-current file",
	})

	vim.api.nvim_create_user_command("ThemeToGhostty", function()
		M.push(vim.g.colors_name or "", { force = true })
	end, {
		desc = "Regenerate the current colorscheme's Ghostty theme from live highlights",
	})

	vim.api.nvim_create_user_command("ThemeToTmux", function()
		M.push_tmux(vim.g.colors_name or "", { force = true })
	end, {
		desc = "Regenerate the current colorscheme's tmux theme from live highlights",
	})

	vim.api.nvim_create_user_command("ThemeCacheClear", function()
		local cleared = M.clear_cache()
		vim.notify(
			("ghostty-mirror: cleared %d generated theme%s")
				:format(#cleared, #cleared == 1 and "" or "s"),
			vim.log.levels.INFO
		)
	end, {
		desc = "Delete every generated Ghostty/tmux theme file (hand-made themes are left untouched)",
	})
end

return M
