-- ghostty-mirror.nvim
-- Mirror Neovim's colorscheme into Ghostty so the terminal flips themes the
-- moment you change colorschemes in nvim.

local M = {}

---@class GhosttyMirrorConfig
---@field themes_dir string Directory Ghostty reads themes from. Defaults to ~/.config/ghostty/themes.
---@field theme_file string Path Ghostty reads the active theme from via config-file include. Defaults to ~/.config/ghostty/theme-current.
---@field keymap string|false Keymap that triggers :ThemeFromGhostty (pulls the theme from the file instead of writing to it). Set to false to skip the keymap.
---@field user_command string|false Name of the user command that pulls the theme from Ghostty's theme-current file. Set to false to skip the command.
---@field regenerate_command string|false Name of the user command that force-regenerates the current colorscheme's theme file from live highlights, overwriting any cached/hand-made file. Set to false to skip the command.
---@field light_variant_suffix string Suffix used when looking for light-mode variant files (e.g. "cyberdream-light"). Set to "" or false to disable.
---@field generate boolean When no theme file exists for a colorscheme, generate one on the fly from Neovim's live highlights and terminal_color_* palette, caching it to themes_dir. Skips silently if the palette is incomplete. Defaults to true.
---@field reload_command string[] Command + args used to tell Ghostty to reload its config. Defaults to `pkill -SIGUSR2 ghostty`.

---@type GhosttyMirrorConfig
local defaults = {
	themes_dir = vim.fn.expand("~/.config/ghostty/themes"),
	theme_file = vim.fn.expand("~/.config/ghostty/theme-current"),
	keymap = "<M-t>",
	user_command = "ThemeFromGhostty",
	regenerate_command = "ThemeToGhostty",
	light_variant_suffix = "-light",
	generate = true,
	reload_command = { "pkill", "-SIGUSR2", "ghostty" },
}

---@type GhosttyMirrorConfig
M.config = vim.deepcopy(defaults)

---Convert a 24-bit color integer (as returned by nvim_get_hl) to "#rrggbb".
---@param n integer|nil
---@return string|nil
local function hex(n)
	if type(n) ~= "number" then return nil end
	return string.format("#%06x", n)
end

---Resolve a highlight group to its effective fg/bg, following links.
---@param name string
---@return table
local function hl(name)
	return vim.api.nvim_get_hl(0, { name = name, link = false })
end

---Name we'd write a generated theme under, honoring the light variant suffix
---when &background is "light" so light/dark caches stay separate.
---@param colorscheme string
---@return string
local function target_name(colorscheme)
	local cfg = M.config
	if cfg.light_variant_suffix and cfg.light_variant_suffix ~= "" and vim.o.background == "light" then
		return colorscheme .. cfg.light_variant_suffix
	end
	return colorscheme
end

---Build the lines of a Ghostty theme file from Neovim's *live* highlight state
---(the currently loaded colorscheme). Returns nil when the colorscheme doesn't
---provide a full 16-color terminal palette (terminal_color_0..15) or lacks a
---Normal fg/bg — we never emit a partial, wrong-looking theme.
---@param colorscheme string
---@return string[]|nil
function M.generate(colorscheme)
	local palette = {}
	for i = 0, 15 do
		local c = vim.g["terminal_color_" .. i]
		if type(c) ~= "string" or c == "" then return nil end
		palette[i] = c
	end

	local normal = hl("Normal")
	local bg, fg = hex(normal.bg), hex(normal.fg)
	if not bg or not fg then return nil end

	local lines = {
		"# Generated by ghostty-mirror.nvim from nvim colorscheme: " .. colorscheme,
		"background = " .. bg,
		"foreground = " .. fg,
	}

	local cursor = hl("Cursor")
	local cc = hex(cursor.bg) or hex(cursor.fg)
	if cc then table.insert(lines, "cursor-color = " .. cc) end

	local visual = hl("Visual")
	local sel = hex(visual.bg)
	if sel then table.insert(lines, "selection-background = " .. sel) end

	table.insert(lines, "")
	for i = 0, 15 do
		table.insert(lines, "palette = " .. i .. "=" .. palette[i])
	end
	return lines
end

---Generate a theme from live highlights and write it to themes_dir.
---@param colorscheme string
---@return string|nil # the theme name written, or nil if generation wasn't possible
function M.write_generated(colorscheme)
	local lines = M.generate(colorscheme)
	if not lines then return nil end
	local name = target_name(colorscheme)
	vim.fn.mkdir(M.config.themes_dir, "p")
	vim.fn.writefile(lines, M.config.themes_dir .. "/" .. name)
	return name
end

---Resolve the Ghostty theme name to write for a given Neovim colorscheme.
---Precedence: a hand-made/cached file wins (honoring the light variant suffix
---when &background is "light"); otherwise, if `generate` is enabled, a theme is
---built on the fly from live highlights and cached to themes_dir.
---@param colorscheme string
---@return string|nil # nil if no file exists and generation isn't possible
function M.resolve(colorscheme)
	local cfg = M.config
	local name = colorscheme
	if
		cfg.light_variant_suffix
		and cfg.light_variant_suffix ~= ""
		and vim.o.background == "light"
		and vim.uv.fs_stat(cfg.themes_dir .. "/" .. name .. cfg.light_variant_suffix)
	then
		name = name .. cfg.light_variant_suffix
	end
	if vim.uv.fs_stat(cfg.themes_dir .. "/" .. name) then
		return name
	end
	if cfg.generate then
		return M.write_generated(colorscheme)
	end
	return nil
end

---Write the resolved theme to the theme file and signal Ghostty to reload.
---@param colorscheme string
---@param opts? { force?: boolean } # force regenerates from live highlights, ignoring any existing file
function M.push(colorscheme, opts)
	local name
	if opts and opts.force then
		name = M.write_generated(colorscheme)
	else
		name = M.resolve(colorscheme)
	end
	if not name then return end
	vim.fn.writefile({ "theme = " .. name }, M.config.theme_file)
	vim.system(M.config.reload_command, { detach = true })
end

---Read the theme name currently set in Ghostty's theme-current file.
---@return string|nil
function M.read_current()
	if vim.fn.filereadable(M.config.theme_file) ~= 1 then return nil end
	local lines = vim.fn.readfile(M.config.theme_file)
	return lines[1] and lines[1]:match("theme%s*=%s*(%S+)") or nil
end

---Apply the colorscheme stored in Ghostty's theme-current file to this Neovim
---instance. Used to pull the active theme into other nvim instances.
function M.pull()
	local theme = M.read_current()
	if not theme then
		vim.notify(
			"ghostty-mirror: could not read theme from " .. M.config.theme_file,
			vim.log.levels.WARN
		)
		return
	end
	vim.cmd.colorscheme(theme)
end

---@param opts? GhosttyMirrorConfig
function M.setup(opts)
	M.config = vim.tbl_deep_extend("force", defaults, opts or {})

	vim.api.nvim_create_autocmd("ColorScheme", {
		group = vim.api.nvim_create_augroup("ghostty-mirror", { clear = true }),
		callback = function(ev) M.push(ev.match) end,
	})

	if M.config.user_command then
		vim.api.nvim_create_user_command(M.config.user_command, M.pull, {
			desc = "Apply the colorscheme currently set in Ghostty's theme-current file",
		})
	end

	if M.config.regenerate_command then
		vim.api.nvim_create_user_command(M.config.regenerate_command, function()
			M.push(vim.g.colors_name or "", { force = true })
		end, {
			desc = "Regenerate the current colorscheme's Ghostty theme from live highlights",
		})
	end

	if M.config.keymap then
		local cmd = M.config.user_command and ("<cmd>" .. M.config.user_command .. "<cr>")
			or function() M.pull() end
		vim.keymap.set("n", M.config.keymap, cmd, { desc = "Pull colorscheme from Ghostty" })
	end
end

return M
